# Generated by Django 4.1.7 on 2023-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmuflow', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
